# Generated by Django 5.2.11 on 2026-03-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('full_name', models.CharField(max_length=128, verbose_name='Full name')),
                ('full_name_en', models.CharField(max_length=128, null=True, verbose_name='Full name')),
                ('full_name_uz', models.CharField(max_length=128, null=True, verbose_name='Full name')),
                ('full_name_ru', models.CharField(max_length=128, null=True, verbose_name='Full name')),
                ('position', models.CharField(max_length=128, verbose_name='Position')),
                ('position_en', models.CharField(max_length=128, null=True, verbose_name='Position')),
                ('position_uz', models.CharField(max_length=128, null=True, verbose_name='Position')),
                ('position_ru', models.CharField(max_length=128, null=True, verbose_name='Position')),
                ('info', models.TextField(verbose_name='Info')),
                ('info_en', models.TextField(null=True, verbose_name='Info')),
                ('info_uz', models.TextField(null=True, verbose_name='Info')),
                ('info_ru', models.TextField(null=True, verbose_name='Info')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'db_table': 'teams',
            },
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='full_name',
            field=models.CharField(max_length=128, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Is read'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
