# Generated by Django 5.2.11 on 2026-02-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(default='authors/default-user.jpg', upload_to='authors/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='blogs/default-blog.jpg', upload_to='blogs/'),
        ),
    ]
