# Generated by Django 5.2.11 on 2026-02-20 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blogs.blogcategory'),
        ),
        migrations.AlterModelTable(
            name='blog',
            table='blog',
        ),
        migrations.AlterModelTable(
            name='blogcategory',
            table='blog_category',
        ),
        migrations.AlterModelTable(
            name='blogtag',
            table='blog_tag',
        ),
    ]
